{% set name = "vacuubrand" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vacuubrand-{{ version }}.tar.gz
  sha256: b7f93a6ca1f20a1bb858b9a11fa63f2957d4696454b084a7b3ccaa52bf2faefd

build:
  entry_points:
    - Vacuubrand = vacuubrand.tango.server:main [tango]
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - connio

test:
  imports:
    - vacuubrand
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tiagocoutinho/vacuubrand
  summary: vacuubrand library
  dev_url: https://github.com/tiagocoutinho/vacuubrand
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rhomspuron
    - tiagocoutinho
